services:
  - type: web
    name: aru-academy-backend
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
